### PR TITLE
Ported Project to dotnetcore 3.0

### PR DESCRIPTION
**Pull request by DarylSmith**

### CODE REVIEW

**Comment by cskardon** [comment]
Hi Daryl,

Thanks for this - unfortunately I can't accept this as you've deleted the README and LICENSE files. Not only that - but all the other files being deleted (things like build.bat) are used by AppVeyor for building and publishing the packages.

**Comment by DarylSmith** [comment]
Hi Chris, apologies -  oversight on my end.  I have added back all the missing files and ensure that build.bat is running

**Comment by cskardon** [comment]
Thanks Daryl,

I suspect with the update, I'll need to fix some things on AppVeyor - but fingers crossed it's not a big deal - and then the nuget stuff should be easy enough!

Chris

**Comment by cskardon** [comment]
OK, all done - shifted from MyGet to AppVeyor - and auto deploying to Nuget as it should have done - it's here [1.0.5-Alpha](https://www.nuget.org/packages/TextRazor.NET/1.0.5-alpha) - excuse the version increase - took a couple of tries to get it working :)

**Comment by DarylSmith** [comment]
Great - glad to hear!

**Pull request merged**
